title: Nikola Paunović
# email: nikola.paunovic1511@gmail.com
description: >
  Senior Backend Engineer · Berlin
github_username: paunik

# GA
google_analytics: G-7QXBRXK8X0

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
